import {vehicleImages} from "./vehicle-images.generated.ts";

export type Vehicle = { lot:string; year:number; make:string; model:string; series:string; vehicleType:"Automobile"; body:string; vehicleClass:string; price:number; retail:number; miles:number; city:string; state:string; damage:string; damageSeverity:number; saleReason:string; imageUrl:string; imageSource:string; imageCredit:string; imageLicense:string; title:"Clean"|"Salvage"; fuel:"Gas"|"Diesel"|"Hybrid"|"Electric"; transmission:"Automatic"|"Manual"; drive:"FWD"|"RWD"|"AWD"|"4WD"; color:string; engine:string; cylinders:number; restraintSystem:string; manufacturedIn:string; accent:string };
export type Sort = "best"|"price-asc"|"price-desc"|"miles"|"newest"|"oldest";
export type Filters = { vehicleTypes:string[]; makes:string[]; excludedMakes:string[]; models:string[]; series:string[]; bodies:string[]; vehicleClasses:string[]; minYear?:number; maxYear?:number; minPrice?:number; maxPrice?:number; minMiles?:number; maxMiles?:number; states:string[]; fuels:string[]; transmissions:string[]; drives:string[]; titles:string[]; damages:string[]; excludedDamages:string[]; colors:string[]; engines:string[]; cylinders:number[]; restraintSystems:string[]; manufacturedIn:string[]; sort:Sort };

type Spec = [string,string,string,Vehicle["fuel"],Vehicle["drive"]];
const specs: Spec[] = [
  ["Toyota","RAV4 XLE","SUV","Gas","AWD"],["Toyota","Highlander LE","SUV","Gas","FWD"],["Toyota","Camry SE","Sedan","Hybrid","FWD"],["Toyota","Tacoma SR5","Truck","Gas","4WD"],
  ["Honda","CR-V EX","SUV","Gas","AWD"],["Honda","Pilot Touring","SUV","Gas","AWD"],["Honda","Accord Sport","Sedan","Hybrid","FWD"],["Honda","Civic EX","Sedan","Gas","FWD"],
  ["Ford","F-150 XLT","Truck","Gas","4WD"],["Ford","Escape SEL","SUV","Hybrid","AWD"],["Ford","Mustang GT","Coupe","Gas","RWD"],["Ford","Transit 250","Van","Gas","RWD"],
  ["Tesla","Model Y","SUV","Electric","AWD"],["Tesla","Model 3","Sedan","Electric","RWD"],["Jeep","Wrangler Sport","SUV","Gas","4WD"],["Jeep","Grand Cherokee","SUV","Gas","4WD"],
  ["Chevrolet","Silverado 1500","Truck","Gas","4WD"],["Chevrolet","Equinox LT","SUV","Gas","FWD"],["Nissan","Rogue SV","SUV","Gas","AWD"],["Nissan","Altima SR","Sedan","Gas","FWD"],
  ["Hyundai","Tucson SEL","SUV","Hybrid","AWD"],["Hyundai","Elantra Limited","Sedan","Gas","FWD"],["Kia","Telluride EX","SUV","Gas","AWD"],["Kia","Carnival LX","Minivan","Gas","FWD"],
  ["BMW","X3 xDrive30i","SUV","Gas","AWD"],["BMW","330i","Sedan","Gas","RWD"],["Mercedes-Benz","GLC 300","SUV","Gas","AWD"],["Audi","Q5 Premium","SUV","Gas","AWD"],
  ["Lexus","RX 350","SUV","Hybrid","AWD"],["Mazda","CX-5 Touring","SUV","Gas","AWD"],["Subaru","Outback Premium","Wagon","Gas","AWD"],["Volkswagen","Golf GTI","Hatchback","Gas","FWD"],
  ["Ram","1500 Big Horn","Truck","Gas","4WD"],["GMC","Sierra 1500","Truck","Diesel","4WD"],["Volvo","XC60 Recharge","SUV","Hybrid","AWD"],["Chrysler","Pacifica Touring","Minivan","Hybrid","FWD"],
  ["Dodge","Challenger R/T","Coupe","Gas","RWD"],["Porsche","Macan S","SUV","Gas","AWD"],["Rivian","R1T Adventure","Truck","Electric","AWD"],["Ford","Bronco Big Bend","SUV","Gas","4WD"],
  ["Chevrolet","Bolt EUV","Hatchback","Electric","FWD"],["Nissan","Leaf SV","Hatchback","Electric","FWD"],["Toyota","Sienna XLE","Minivan","Hybrid","AWD"],["Mazda","MX-5 Miata","Convertible","Gas","RWD"],
  ["Subaru","WRX Premium","Sedan","Gas","AWD"],["Volkswagen","Atlas SE","SUV","Gas","AWD"],["GMC","Yukon SLT","SUV","Gas","4WD"],["Ram","ProMaster 2500","Van","Gas","FWD"],
  ["Kia","EV6 Wind","SUV","Electric","AWD"],["Hyundai","Ioniq 5 SEL","SUV","Electric","AWD"],["Audi","A5 Cabriolet","Convertible","Gas","AWD"],["BMW","M4 Competition","Coupe","Gas","RWD"],
  ["Mercedes-Benz","Sprinter 2500","Van","Diesel","RWD"],["Lexus","ES 300h","Sedan","Hybrid","FWD"],["Volvo","V60 Cross Country","Wagon","Gas","AWD"],["Jeep","Gladiator Rubicon","Truck","Gas","4WD"],
];
const places=[['Dallas','TX'],['Houston','TX'],['Austin','TX'],['Phoenix','AZ'],['Denver','CO'],['Los Angeles','CA'],['Miami','FL'],['Atlanta','GA'],['Chicago','IL'],['Las Vegas','NV'],['Albany','NY'],['Seattle','WA']];
const damages=["Minor Dent","Front End","Rear End","Side","Hail","Flood","Vandalism","Normal Wear"];
const colors=["Black","White","Silver","Gray","Blue","Red","Green","Tan"];
const accents=["#26323a","#e7e4dc","#aeb5b7","#70777a","#315d77","#a84638","#536348","#9a8060"];
const cleanSaleReasons=["Fleet vehicle released during a scheduled inventory refresh.","Dealer trade-in offered through wholesale auction.","Lease-return vehicle being remarketed by the finance company.","Rental fleet unit retired after completing its planned service cycle.","Repossessed vehicle offered for sale by the secured lender.","Company vehicle replaced as part of a routine fleet upgrade."];
const salvageSaleReasons:Record<string,string>={"Minor Dent":"Insurance recovery offered after a minor body-damage claim.","Front End":"Insurance total-loss recovery following a front-end collision.","Rear End":"Insurance total-loss recovery following a rear-impact claim.",Side:"Insurance recovery following a side-impact damage claim.",Hail:"Insurance total-loss recovery following storm and hail damage.",Flood:"Insurance total-loss recovery following reported water exposure.",Vandalism:"Insurance recovery following a reported vandalism claim.","Normal Wear":"High-mileage fleet vehicle released for parts or repair."};
const damageBase:Record<string,number>={"Minor Dent":10,"Front End":48,"Rear End":36,Side:40,Hail:24,Flood:62,Vandalism:20,"Normal Wear":7};
const originByMake:Record<string,string>={Toyota:"Japan",Honda:"Japan",Ford:"United States",Tesla:"United States",Jeep:"United States",Chevrolet:"United States",Nissan:"Japan",Hyundai:"South Korea",Kia:"South Korea",BMW:"Germany","Mercedes-Benz":"Germany",Audi:"Germany",Lexus:"Japan",Mazda:"Japan",Subaru:"Japan",Volkswagen:"Germany",Ram:"United States",GMC:"United States",Volvo:"Sweden",Chrysler:"United States",Dodge:"United States",Porsche:"Germany",Rivian:"United States"};
const restraintOptions=["Front and side airbags; overhead airbags","Front airbags; side curtain airbags","Advanced front airbags; knee airbags; side curtain airbags"];
const seriesFor=(model:string)=>model.split(" ").slice(1).join(" ")||"Base";
const engineFor=(fuel:Vehicle["fuel"],body:string,i:number)=>fuel==="Electric"?"Dual electric motor":fuel==="Hybrid"?(i%2?"2.5L hybrid":"2.0L hybrid"):fuel==="Diesel"?(body==="Truck"?"3.0L turbo diesel":"2.0L turbo diesel"):(body==="Truck"?"5.0L V8":body==="SUV"?"2.5L":"1.8L");
const cylindersFor=(fuel:Vehicle["fuel"],body:string,i:number)=>fuel==="Electric"?0:body==="Truck"?8:(body==="SUV"&&i%3===0?6:4);

export const inventory: Vehicle[] = Array.from({length:200},(_,i)=>{const [make,model,body,fuel,drive]=specs[i%specs.length]; const [city,state]=places[(i*5+Math.floor(i/specs.length))%places.length]; const year=2014+((i*7+Math.floor(i/9))%12); const price=5500+((i*4387+Math.floor(i/specs.length)*1739)%69500);const damage=damages[(i*3+Math.floor(i/specs.length))%damages.length];const title=i%3===0?"Salvage":"Clean";const damageSeverity=Math.min(88,damageBase[damage]+(i%7)+(title==="Salvage"?12:0));const image=vehicleImages[`${make}|${model}`];return {lot:String(51000000+i*7919),make,model,series:seriesFor(model),vehicleType:"Automobile",body,vehicleClass:body,fuel,drive,city,state,year,price,retail:Math.round(price*1.48),miles:6200+((i*11873+Math.floor(i/specs.length)*3901)%126000),damage,damageSeverity,saleReason:title==="Salvage"?salvageSaleReasons[damage]:cleanSaleReasons[i%cleanSaleReasons.length],imageUrl:image.path,imageSource:image.source,imageCredit:image.credit,imageLicense:image.license,title,transmission:i%11===0?"Manual":"Automatic",color:colors[(i*5)%colors.length],engine:engineFor(fuel,body,i),cylinders:cylindersFor(fuel,body,i),restraintSystem:restraintOptions[i%restraintOptions.length],manufacturedIn:originByMake[make],accent:accents[(i*3)%accents.length]};});

export const emptyFilters=():Filters=>({vehicleTypes:[],makes:[],excludedMakes:[],models:[],series:[],bodies:[],vehicleClasses:[],states:[],fuels:[],transmissions:[],drives:[],titles:[],damages:[],excludedDamages:[],colors:[],engines:[],cylinders:[],restraintSystems:[],manufacturedIn:[],sort:"best"});
const makeNames=[...new Set(inventory.map(v=>v.make))]; const modelNames=[...new Set(inventory.map(v=>v.model))]; const seriesNames=[...new Set(inventory.map(v=>v.series))]; const bodyNames=[...new Set(inventory.map(v=>v.body))]; const engineNames=[...new Set(inventory.map(v=>v.engine))]; const origins=[...new Set(inventory.map(v=>v.manufacturedIn))];
const states:Record<string,string>={texas:"TX",arizona:"AZ",colorado:"CO",california:"CA",florida:"FL",georgia:"GA",illinois:"IL",nevada:"NV","new york":"NY",washington:"WA",tx:"TX",az:"AZ",co:"CO",ca:"CA",fl:"FL",ga:"GA",il:"IL",nv:"NV",ny:"NY",wa:"WA"};
const money=(match:RegExpMatchArray)=>Math.round(Number(match[1].replace(/,/g,""))*(match[2]?1000:1));
const list=(values:string[],found:string[],add:boolean)=>add?[...new Set([...values,...found])]:found;
const SEARCH_LANGUAGE=`automobile vehicle vehicles car cars make brand model series body style class exterior color engine transmission fuel gasoline gas diesel hybrid electric cylinder cylinders restraint system manufactured made country location state title clean salvage damage mileage miles odometer drive front rear side hail flood vandalism wear automatic manual budget price bid minimum maximum under below less than above over more at least between from through after before newer older later range include exclude without remove reset clear undo compare best cheapest highest lowest sort show available preference anywhere nationwide want need looking find give which what something only with have should could please maybe like new search start instead`.split(/\s+/);
const inventoryVocabulary=[...makeNames,...modelNames,...seriesNames,...bodyNames,...engineNames,...origins,...damages,...colors,...Object.keys(states),...inventory.flatMap(vehicle=>[vehicle.vehicleType,vehicle.vehicleClass,vehicle.fuel,vehicle.transmission,vehicle.drive,vehicle.title,vehicle.restraintSystem])];
const correctionTerms=[...new Set([...inventoryVocabulary,...SEARCH_LANGUAGE].flatMap(value=>value.toLowerCase().match(/[a-z0-9-]+/g)||[]).filter(value=>value.length>=4))];
const editDistance=(a:string,b:string)=>{const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let previous=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const saved=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,previous+(a[i-1]===b[j-1]?0:1));previous=saved;}}const distance=row[b.length];if(distance===2&&a.length===b.length){const differences=[...a].map((char,index)=>char===b[index]?-1:index).filter(index=>index>=0);if(differences.length===2&&differences[1]===differences[0]+1&&a[differences[0]]===b[differences[1]]&&a[differences[1]]===b[differences[0]])return 1;}return distance;};
export function correctSearchText(input:string){return input.replace(/[A-Za-z][A-Za-z0-9-]{3,}/g,word=>{const lower=word.toLowerCase();if(correctionTerms.includes(lower))return word;const max=lower.length>=6?2:1;const matches=correctionTerms.map(term=>({term,distance:editDistance(lower,term)})).filter(match=>match.term[0]===lower[0]&&Math.abs(match.term.length-lower.length)<=2&&match.distance<=max).sort((a,b)=>a.distance-b.distance);return matches.length&&(!matches[1]||matches[0].distance<matches[1].distance)?matches[0].term:word;});}

export function shouldClarifySearchIntent(input:string,current:Filters){
  if(!filterLabels(current).length)return false;
  const q=correctSearchText(input).toLowerCase().trim();
  if(/^(?:please\s+)?(?:new search|start over|instead,?\s+(?:find|show me|give me)|make it|change|switch|actually|only|also|now|and|but|add|include|exclude|without|remove|reset|clear|undo)\b/.test(q))return false;
  const requestOpening=/^(?:please\s+)?(?:give|show|find|i want|i need|looking for|can you (?:find|show|give))\b/.test(q);
  const compactVehicleRequest=/^(?:[a-z0-9$,-]+\s+){0,5}(?:cars?|vehicles?|automobiles?)\b/.test(q);
  const namedVehicleTarget=makeNames.some(make=>q.includes(make.toLowerCase()))||modelNames.some(model=>q.includes(model.toLowerCase()))||bodyNames.some(body=>new RegExp(`\\b${body.toLowerCase()}s?\\b`).test(q));
  return requestOpening||compactVehicleRequest||namedVehicleTarget;
}

export function updateFilters(input:string,current:Filters):Filters{
  const q=correctSearchText(input).toLowerCase();
  const requestedBodies=bodyNames.filter(x=>new RegExp(`\\b${x.toLowerCase()}s?\\b`).test(q));
  const explicitFreshSearch=/^(?:please\s+)?(?:new search\b(?=\s*[:,-]?\s+\S)|start over\s+(?:with|and find|looking for)\b|instead,?\s+(?:find|show me|give me)\b)/.test(q);
  const refinementCue=/^(?:please\s+)?(?:make it|change|switch|actually|only|also|now|and|but|add|include|exclude|without|remove)\b/.test(q);
  const categorySwitch=requestedBodies.length>0&&current.bodies.length>0&&!requestedBodies.some(body=>current.bodies.includes(body))&&!refinementCue;
  const freshSearch=explicitFreshSearch||categorySwitch;
  if(!freshSearch&&/reset|start over|clear (all|search|filters)|show (me )?(all|every) (cars?|vehicles?|inventory)( available)?|all (cars?|vehicles?) available/.test(q)) return emptyFilters();
  const base=freshSearch?emptyFilters():current; const next={...base,...Object.fromEntries(Object.entries(base).map(([k,v])=>[k,Array.isArray(v)?[...v]:v]))} as Filters;
  const remove=/remove|any |no preference|doesn.?t matter/.test(q); const additive=/include|also| or |add /.test(q);
  if(/undo/.test(q)) return next;
  if(/remove (the )?(price|budget)|any price/.test(q)){delete next.minPrice;delete next.maxPrice;} if(/remove (the )?(year|age)|any year/.test(q)){delete next.minYear;delete next.maxYear;} if(/remove (the )?(mileage|miles)|any mileage/.test(q)){delete next.minMiles;delete next.maxMiles;}
  if(/remove (the )?(location|state)|anywhere|nationwide/.test(q))next.states=[]; if(/remove (the )?(make|brand)|any make/.test(q)){next.makes=[];next.excludedMakes=[];} if(/remove (the )?(body|type)|any body/.test(q))next.bodies=[];
  if(/\b(automobile|automobiles|car|cars)\b/.test(q))next.vehicleTypes=["Automobile"];
  const mentionedMakes=makeNames.filter(x=>q.includes(x.toLowerCase())); const negativeMake=/\b(no|exclude|without)\b/.test(q); if(mentionedMakes.length){if(negativeMake)next.excludedMakes=list(next.excludedMakes,mentionedMakes,true);else{next.makes=list(next.makes,mentionedMakes,additive);next.excludedMakes=next.excludedMakes.filter(x=>!mentionedMakes.includes(x));}}
  const mentionedModels=modelNames.filter(x=>q.includes(x.toLowerCase())); if(mentionedModels.length)next.models=list(next.models,mentionedModels,additive);
  const mentionedSeries=seriesNames.filter(x=>new RegExp(`\\bseries\\s+${x.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`).test(q));if(mentionedSeries.length)next.series=list(next.series,mentionedSeries,additive);
  if(requestedBodies.length)next.bodies=list(next.bodies,requestedBodies,additive);
  for(const [name,code] of Object.entries(states))if(new RegExp(`\\b${name}\\b`).test(q))next.states=list(next.states,[code],additive);
  const rangeYear=q.match(/(?:between|from)?\s*(20\d{2}|19\d{2})\s*(?:and|to|through|-)\s*(20\d{2}|19\d{2})/); if(rangeYear){next.minYear=Math.min(+rangeYear[1],+rangeYear[2]);next.maxYear=Math.max(+rangeYear[1],+rangeYear[2]);}else{const strictlyAfter=q.match(/(?:after|later than|newer than)\s*(20\d{2}|19\d{2})/);const newer=q.match(/(20\d{2}|19\d{2})\s*(?:or newer|\+|and newer|or later)/);const older=q.match(/(?:before|through|up to|no newer than|or older)\s*(20\d{2}|19\d{2})|(20\d{2}|19\d{2})\s*(?:or older)/);const exact=q.match(/(?:model(?:\s+year)?\s*)?(20\d{2}|19\d{2})\s*(?:model|models|model year|only|year)?\b/);if(strictlyAfter){next.minYear=+strictlyAfter[1]+1;delete next.maxYear;}else if(newer){next.minYear=+newer[1];delete next.maxYear;}else if(older){next.maxYear=+(older[1]||older[2]);delete next.minYear;}else if(exact){next.minYear=+exact[1];next.maxYear=+exact[1];}}
  const rangePrice=q.match(/between\s*\$?([\d,.]+)\s*(k|grand)?\s*(?:and|to)\s*\$?([\d,.]+)\s*(k|grand)?/); if(rangePrice){next.minPrice=money(rangePrice);next.maxPrice=Math.round(Number(rangePrice[3].replace(/,/g,""))*(rangePrice[4]?1000:1));}else{const max=q.match(/(?:under|below|less than|max(?:imum)?|budget(?: of)?)\s*\$?([\d,.]+)\s*(k|grand)?/);if(max){next.maxPrice=money(max);delete next.minPrice;}const min=q.match(/(?:above|over|more than|at least|min(?:imum)?)\s*\$?([\d,.]+)\s*(k|grand)?/);if(min){next.minPrice=money(min);delete next.maxPrice;}}
  const maxMiles=q.match(/(?:under|below|less than|max(?:imum)?)\s*([\d,.]+)\s*(k)?\s*(?:miles|mi|mileage)/); if(maxMiles)next.maxMiles=Math.round(Number(maxMiles[1].replace(/,/g,""))*(maxMiles[2]?1000:1)); if(/low(?:er)? mileage|fewest miles/.test(q)){next.maxMiles=next.maxMiles??60000;next.sort="miles";}
  const fuels=["Gas","Diesel","Hybrid","Electric"].filter(x=>new RegExp(`\\b${x.toLowerCase()}\\b`).test(q));if(/\bgasoline\b/.test(q)&&!fuels.includes("Gas"))fuels.push("Gas"); if(fuels.length)next.fuels=list(next.fuels,fuels,additive); const transmissions=["Automatic","Manual"].filter(x=>q.includes(x.toLowerCase()));if(transmissions.length)next.transmissions=list(next.transmissions,transmissions,additive); const drives=["FWD","RWD","AWD","4WD"].filter(x=>new RegExp(`\\b${x.toLowerCase()}\\b`).test(q));if(drives.length)next.drives=list(next.drives,drives,additive);
  const titles=["Clean","Salvage"].filter(x=>q.includes(`${x.toLowerCase()} title`)||q.includes(`${x.toLowerCase()} titles`));if(titles.length)next.titles=list(next.titles,titles,additive); if(/any title/.test(q))next.titles=[];
  const mentionedDamages=damages.filter(x=>q.includes(x.toLowerCase()));if(mentionedDamages.length){if(/no |exclude|without/.test(q))next.excludedDamages=list(next.excludedDamages,mentionedDamages,true);else next.damages=list(next.damages,mentionedDamages,additive);}
  const mentionedColors=colors.filter(x=>new RegExp(`\\b${x.toLowerCase()}\\b`).test(q));if(mentionedColors.length)next.colors=list(next.colors,mentionedColors,additive);
  const mentionedEngines=engineNames.filter(x=>q.includes(x.toLowerCase()));if(mentionedEngines.length)next.engines=list(next.engines,mentionedEngines,additive);
  const cylinder=q.match(/\b(0|4|6|8)[ -]?(?:cylinder|cylinders|cyl)\b/);if(cylinder)next.cylinders=list(next.cylinders,[+cylinder[1]],additive);
  const mentionedOrigins=origins.filter(x=>q.includes(`made in ${x.toLowerCase()}`)||q.includes(`manufactured in ${x.toLowerCase()}`));if(mentionedOrigins.length)next.manufacturedIn=list(next.manufacturedIn,mentionedOrigins,additive);
  if(/front and side airbags|overhead airbags/.test(q))next.restraintSystems=list(next.restraintSystems,["Front and side airbags; overhead airbags"],additive);
  if(/sort by (lowest )?price|cheapest|cheaper/.test(q))next.sort="price-asc";if(/highest price/.test(q))next.sort="price-desc";if(/newest/.test(q))next.sort="newest";if(/oldest/.test(q))next.sort="oldest";if(/sort by mileage|fewest miles/.test(q))next.sort="miles";if(remove&&/fuel/.test(q))next.fuels=[];
  return next;
}

export function searchVehicles(f:Filters){return inventory.filter(v=>(!f.vehicleTypes.length||f.vehicleTypes.includes(v.vehicleType))&&(!f.makes.length||f.makes.includes(v.make))&&!f.excludedMakes.includes(v.make)&&(!f.models.length||f.models.includes(v.model))&&(!f.series.length||f.series.includes(v.series))&&(!f.bodies.length||f.bodies.includes(v.body))&&(!f.vehicleClasses.length||f.vehicleClasses.includes(v.vehicleClass))&&(!f.minYear||v.year>=f.minYear)&&(!f.maxYear||v.year<=f.maxYear)&&(!f.minPrice||v.price>=f.minPrice)&&(!f.maxPrice||v.price<=f.maxPrice)&&(!f.minMiles||v.miles>=f.minMiles)&&(!f.maxMiles||v.miles<=f.maxMiles)&&(!f.states.length||f.states.includes(v.state))&&(!f.fuels.length||f.fuels.includes(v.fuel))&&(!f.transmissions.length||f.transmissions.includes(v.transmission))&&(!f.drives.length||f.drives.includes(v.drive))&&(!f.titles.length||f.titles.includes(v.title))&&(!f.damages.length||f.damages.includes(v.damage))&&!f.excludedDamages.includes(v.damage)&&(!f.colors.length||f.colors.includes(v.color))&&(!f.engines.length||f.engines.includes(v.engine))&&(!f.cylinders.length||f.cylinders.includes(v.cylinders))&&(!f.restraintSystems.length||f.restraintSystems.includes(v.restraintSystem))&&(!f.manufacturedIn.length||f.manufacturedIn.includes(v.manufacturedIn))).sort((a,b)=>f.sort==="price-asc"?a.price-b.price:f.sort==="price-desc"?b.price-a.price:f.sort==="miles"?a.miles-b.miles:f.sort==="oldest"?a.year-b.year:b.year-a.year);}
export function filterLabels(f:Filters){const out:string[]=[];if(f.vehicleTypes.length)out.push(f.vehicleTypes.join(" or "));if(f.makes.length)out.push(f.makes.join(" or "));if(f.excludedMakes.length)out.push(`No ${f.excludedMakes.join("/")}`);if(f.models.length)out.push(f.models.join(" or "));if(f.series.length)out.push(`Series ${f.series.join(" or ")}`);if(f.bodies.length)out.push(f.bodies.join(" or "));if(f.vehicleClasses.length)out.push(`${f.vehicleClasses.join(" or ")} class`);if(f.minYear&&f.maxYear)out.push(f.minYear===f.maxYear?`${f.minYear} only`:`${f.minYear}–${f.maxYear}`);else if(f.minYear)out.push(`${f.minYear}+`);else if(f.maxYear)out.push(`Through ${f.maxYear}`);if(f.minPrice)out.push(`Above $${Math.round(f.minPrice/1000)}k`);if(f.maxPrice)out.push(`Under $${Math.round(f.maxPrice/1000)}k`);if(f.maxMiles)out.push(`≤ ${Math.round(f.maxMiles/1000)}k mi`);if(f.states.length)out.push(f.states.join(" or "));if(f.fuels.length)out.push(f.fuels.map(x=>x==="Gas"?"Gasoline":x).join(" or "));if(f.transmissions.length)out.push(f.transmissions.join(" or "));if(f.drives.length)out.push(f.drives.join(" or "));if(f.titles.length)out.push(`${f.titles.join(" or ")} title`);if(f.excludedDamages.length)out.push(`No ${f.excludedDamages.join("/")} damage`);if(f.colors.length)out.push(f.colors.join(" or "));if(f.engines.length)out.push(f.engines.join(" or "));if(f.cylinders.length)out.push(`${f.cylinders.join(" or ")} cylinders`);if(f.restraintSystems.length)out.push("Selected restraints");if(f.manufacturedIn.length)out.push(`Made in ${f.manufacturedIn.join(" or ")}`);return out;}
